"""Initial migration

Revision ID: 8b6a93bcc4d3
Revises: 6a9fa1d57088
Create Date: 2024-12-09 18:04:55.360259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b6a93bcc4d3'
down_revision: Union[str, None] = '6a9fa1d57088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
